services:
  db:
    image: postgres:16-alpine
    container_name: elax_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  
  bot:
    build: .
    container_name: elax_bot
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "${WG_PORT}:${WG_PORT}/udp"
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

volumes:
  pgdata:
